CREATE TABLE IF NOT EXISTS T_EO_A_AttributeDefinitions (
    _ScenarioID INT NOT NULL,
    ObjectName VARCHAR(255) ,
    _VariableTypeAndConstraintSetControl VARCHAR(255),
    _ForceMinRatiosOnAttributesDefaultValue VARCHAR(255),
    _AnalysisFlag VARCHAR(255),
    _CopyTagFieldsToAdjustmentTables VARCHAR(255),
    _CurrencyAdjustPeriodBiases VARCHAR(255),
    Facility VARCHAR(255),
    Attribute VARCHAR(255) NOT NULL,
    OnOff VARCHAR(255),
    Tag1 VARCHAR(255),
    Tag2 VARCHAR(255),
    AttributeType VARCHAR(255),
    TotallerType VARCHAR(255),
    ObjectClassAppliedTo VARCHAR(255),
    UseAsDefaultForObjects VARCHAR(255),
    ConstraintType VARCHAR(255),
    SoftConstraintBias FLOAT,
    TotalActivityBias FLOAT,
    PeriodActivityBias FLOAT,
    FacilityForDrivingBiasToPAndL VARCHAR(255),
    VariableUnitAdjustment FLOAT,
    TotalFixedAdjustment FLOAT,
    MinUnitsOrValuePerPeriod FLOAT,
    MaxUnitsOrValuePerPeriod FLOAT,
    MinTotalUnitsOrValue FLOAT,
    MaxTotalUnitsOrValue FLOAT,
    TotalSolutionUnitsOrValue FLOAT,
    OppValuePerUnitOrValue FLOAT,
    TotalPrimaryVolumeIn FLOAT,
    TotalPrimaryVolumeOut FLOAT,
    MinEndingBalanceLastPeriod FLOAT,
    MaxEndingBalanceLastPeriod FLOAT,
    SolutionEndingBalanceLastPeriod FLOAT,
    OppValueEndingBalanceLastPeriod FLOAT,
    MinCarryforwardBalance FLOAT,
    MaxCarryforwardBalance FLOAT,
    VariableType VARCHAR(255),
    ConstraintSet VARCHAR(255)
);