CREATE TABLE IF NOT EXISTS T_EO_C_ConstraintSetDefinitions (
    _ScenarioID INT NOT NULL,
    ObjectName VARCHAR(255),
    Facility VARCHAR(255),
    ConstraintSet VARCHAR(255),
    Tag1 VARCHAR(255),
    Tag2 VARCHAR(255),
    Attribute1 VARCHAR(255),
    Attribute2 VARCHAR(255),
    Attribute3 VARCHAR(255),
    Attribute4 VARCHAR(255),
    OnOff VARCHAR(255),
    ConstraintSetType VARCHAR(255),
    ReportType VARCHAR(255),
    BiasPerElement FLOAT,
    MinActivityPerElement FLOAT,
    MinActiveSetElementsPerPeriod FLOAT,
    MaxActiveSetElementsPerPeriod FLOAT,
    MinTotalActiveSetElements FLOAT,
    MaxTotalActiveSetElements FLOAT,
    TotalActiveSetElements FLOAT,
    OppValuePerActiveSetElement FLOAT,
    InfeasibilityShortage FLOAT,
    InfeasibilityExcess FLOAT
);