CREATE TABLE IF NOT EXISTS EO_C_ConstraintSetDefinitions (
    _ScenarioID INT,
    ObjectName VARCHAR,
    Facility VARCHAR,
    ConstraintSet VARCHAR,
    Tag1 VARCHAR,
    Tag2 VARCHAR,
    Attribute1 VARCHAR,
    Attribute2 VARCHAR,
    Attribute3 VARCHAR,
    Attribute4 VARCHAR,
    OnOff VARCHAR,
    ConstraintSetType VARCHAR,
    ReportType VARCHAR,
    BiasPerElement FLOAT,
    MinActivityPerElement FLOAT,
    MinActiveSetElementsPerPeriod FLOAT,
    MaxActiveSetElementsPerPeriod FLOAT,
    MinTotalActiveSetElements FLOAT,
    MaxTotalActiveSetElements FLOAT,
    TotalActiveSetElements FLOAT,
    OppValuePerActiveSetElement FLOAT,
    InfeasibilityShortage FLOAT,
    InfeasibilityExcess FLOAT
);