CREATE TABLE IF NOT EXISTS T_EO_E_LocationDefinitionsMTP (
    _ScenarioID INT NOT NULL,
    ObjectName VARCHAR(255) NOT NULL,
    _BaseCurrency VARCHAR(255),
    _InfeasibilityFlag VARCHAR(255),
    _WarningMessageFlag VARCHAR(255),
    _FinancialReportFlag VARCHAR(255),
    _TypeOfAutofill VARCHAR(255),
    _AttributeControl VARCHAR(255),
    _NumberOfStoredSolutions INT,
    _DefaultFillFlag VARCHAR(255),
    _ForceMinRatios VARCHAR(255),
    _SuppressActivityForClosedFacilitiesAndLocations VARCHAR(255),
    _DiscountApproximationSteps INT,
    _RunAdvancedDatacheckAutomatically VARCHAR(255),
    _AutomationDialogSuppressionFlag BOOLEAN,
    _IncludeFixedCostsInUnitCosts BOOLEAN,
    _UnitCostObjectiveParameter BOOLEAN,
    _ComputeDUC BOOLEAN,
    _DUCToUnitCostComparisonFactor FLOAT,
    _UseDiscountCurves VARCHAR(255),
    _AutomaticallyGenerateStochasticValues VARCHAR(255),
    _DefaultStochasticDistribution VARCHAR(255),
    _UseStochasticSeedFromVariable VARCHAR(255),
    _StochasticSeedValue INT ,
    _PropagateTagsToMTPTable VARCHAR(255),
    TimePeriod VARCHAR(255) NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Facility VARCHAR(255),
    Attribute1 VARCHAR(255),
    Attribute2 VARCHAR(255),
    Attribute3 VARCHAR(255),
    Attribute4 VARCHAR(255),
    FixedCostOpen FLOAT,
    FixedCostClosed FLOAT,
    OTPremium FLOAT,
    PayrollLoadFactor FLOAT,
    STSlackSwitch VARCHAR(255),
    OTSlackSwitch VARCHAR(255),
    DecisionSwitch VARCHAR(255),
    Decision FLOAT,
    DecisionOppValue FLOAT,
    FixedCostOpenFactor FLOAT,
    FixedCostOpenAdd FLOAT,
    FixedCostClosedFactor FLOAT,
    FixedCostClosedAdd FLOAT,
    OTPremiumFactor FLOAT,
    OTPremiumAdd FLOAT,
    PayrollLoadFactorFactor FLOAT,
    PayrollLoadFactorAdd FLOAT,
    PurchaseUnits FLOAT,
    InventoryOutflowUnits FLOAT,
    InventoryEndingUnits FLOAT,
    ProcessUnits FLOAT,
    ResourceHours FLOAT,
    SalesUnits FLOAT,
    Tag1 VARCHAR(255),
    Tag2 VARCHAR(255)
);