CREATE TABLE IF NOT EXISTS T_EO_E_TimePeriodDefinitions (
    _ScenarioID INT NOT NULL,
    --ObjectName VARCHAR(255) ,
    --_BaseCurrency VARCHAR(255),
    --_InfeasibilityFlag VARCHAR(255),
    --_WarningMessageFlag VARCHAR(255),
    --_FinancialReportFlag VARCHAR(255),
    --_TypeOfAutofill VARCHAR(255),
    --_AttributeControl VARCHAR(255),
    --_NumberOfStoredSolutions INT,
    --_DefaultFillFlag VARCHAR(255),
    --_ForceMinRatios VARCHAR(255),
    --_SuppressActivityForClosedFacilitiesAndLocations VARCHAR(255),
    --_DiscountApproximationSteps INT,
    --_RunAdvancedDatacheckAutomatically VARCHAR(255),
    --_AutomationDialogSuppressionFlag BOOLEAN,
    --_IncludeFixedCostsInUnitCosts BOOLEAN,
    --_UnitCostObjectiveParameter BOOLEAN,
    --_ComputeDUC BOOLEAN,
    --_DUCToUnitCostComparisonFactor FLOAT,
    --_UseDiscountCurves VARCHAR(255),
    --_AutomaticallyGenerateStochasticValues VARCHAR(255),
    --_DefaultStochasticDistribution VARCHAR(255),
    --_UseStochasticSeedFromVariable VARCHAR(255),
    --_StochasticSeedValue INT,
    --_PropagateTagsToMTPTable VARCHAR(255),
    TimePeriod VARCHAR(255) NOT NULL,
    PeriodLengthFactor FLOAT DEFAULT 1,
    Tag1 VARCHAR(255),
    Tag2 VARCHAR(255),
    Counter1 INT DEFAULT 0,
    Counter2 INT DEFAULT 0,
    PeriodIndex INT
);