CREATE TABLE IF NOT EXISTS T_EO_E_LocationDefinitions (
    _ScenarioID INT NOT NULL,
    ObjectName VARCHAR(255) ,
    _BaseCurrency VARCHAR(255),
    _InfeasibilityFlag VARCHAR(255),
    _WarningMessageFlag VARCHAR(255),
    _FinancialReportFlag VARCHAR(255),
    _TypeOfAutofill VARCHAR(255),
    _AttributeControl VARCHAR(255),
    _NumberOfStoredSolutions INT,
    _DefaultFillFlag VARCHAR(255),
    _ForceMinRatios VARCHAR(255),
    _SuppressActivityForClosedFacilitiesAndLocations VARCHAR(255),
    _DiscountApproximationSteps INT,
    _RunAdvancedDatacheckAutomatically VARCHAR(255),
    _AutomationDialogSuppressionFlag BOOLEAN,
    _IncludeFixedCostsInUnitCosts BOOLEAN,
    _UnitCostObjectiveParameter BOOLEAN,
    _ComputeDUC BOOLEAN,
    _DUCToUnitCostComparisonFactor FLOAT,
    _UseDiscountCurves VARCHAR(255),
    _AutomaticallyGenerateStochasticValues VARCHAR(255),
    _DefaultStochasticDistribution VARCHAR(255),
    _UseStochasticSeedFromVariable VARCHAR(255),
    _StochasticSeedValue INT,
    _PropagateTagsToMTPTable VARCHAR(255),
    Location VARCHAR(255) NOT NULL,
    Facility VARCHAR(255),
    UseAsDefault VARCHAR(255),
    Attribute1 VARCHAR(255),
    Attribute2 VARCHAR(255),
    Attribute3 VARCHAR(255),
    Attribute4 VARCHAR(255),
    Currency VARCHAR(255),
    FixedCostOpen FLOAT,
    FixedCostClosed FLOAT,
    OTPremium FLOAT,
    PayrollLoadFactor FLOAT,
    STSlackSwitch VARCHAR(255),
    OTSlackSwitch VARCHAR(255),
    DecisionSwitch VARCHAR(255),
    MinOpenPeriods FLOAT,
    MaxOpenPeriods FLOAT,
    TotalOpenPeriods FLOAT,
    TotalClosedPeriods FLOAT,
    OpenPeriodInfeasibilityShortage FLOAT,
    OpenPeriodInfeasibilityExcess FLOAT,
    OTPremiumFactor FLOAT,
    OTPremiumAdd FLOAT,
    PayrollLoadFactorFactor FLOAT,
    PayrollLoadFactorAdd FLOAT,
    Tag1 VARCHAR(255),
    Tag2 VARCHAR(255)
);