CREATE TABLE IF NOT EXISTS t_eo_its_mixdistribution (
    _ScenarioID INTEGER NOT NULL,
    objectname VARCHAR(120) NOT NULL,
    fromobjectname VARCHAR(255),
    toobjectname VARCHAR(255),
    _variablecontrolledfacilitylocationattribute VARCHAR(255),
    _onetooneflag VARCHAR(255),
    _distributedmixflag VARCHAR(255),
    _transfercurrencycontrol VARCHAR(255),
    _attribute1 VARCHAR(255),
    _attribute2 VARCHAR(255),
    _attribute3 VARCHAR(255),
    _attribute4 VARCHAR(255),
    _tag1 VARCHAR(255),
    _tag2 VARCHAR(255),
    _tag3 VARCHAR(255),
    fromfacility VARCHAR(255),
    tofacility VARCHAR(255),
    fromlocation VARCHAR(120) NOT NULL,
    tolocation VARCHAR(120) NOT NULL,
    material VARCHAR(255) NOT NULL,
    itemdescription VARCHAR(255) NOT NULL,
    attribute1 VARCHAR(255),
    attribute2 VARCHAR(255),
    attribute3 VARCHAR(255),
    attribute4 VARCHAR(255),
    distribution FLOAT,
    costperunit FLOAT,
    othercostperunit FLOAT,
    transferpriceperunit FLOAT,
    minunitsperperiod FLOAT,
    maxunitsperperiod FLOAT,
    transittime INTEGER,
    totalsolutionunits FLOAT,
    maxoppvalueperunit FLOAT,
    totalcost FLOAT,
    totalunitsintransitlastperiod FLOAT,
    avgcostperincomingunit FLOAT,
    avgcostperoutgoingunit FLOAT,
    fromunittype VARCHAR(255),
    tounittype VARCHAR(255),
    unitconversionfactor FLOAT
);
