CREATE TABLE t_eo_iti_transferactivity (
    _ScenarioID int NOT NULL,
    ObjectName varchar(120) NOT NULL,
    FromObjectName varchar(255) NULL,
    ToObjectName varchar(255) NULL,
    _VariableControlledFacilityLocationAttribute varchar(255) NULL,
    _VariableTypeAndConstraintSetControl varchar(255) NULL,
    _ForceIntegerTransfers varchar(255) NULL,
    _TransferCurrencyControl varchar(255) NULL,
    _Attribute1 varchar(255) NULL,
    _Attribute2 varchar(255) NULL,
    _Attribute3 varchar(255) NULL,
    _Attribute4 varchar(255) NULL,
    _Tag1 varchar(255) NULL,
    _Tag2 varchar(255) NULL,
    _Tag3 varchar(255) NULL,
    _PropagateTagsToMTPTable varchar(255) NULL,
    FromFacility varchar(255) NULL,
    ToFacility varchar(255) NULL,
    FromLocation varchar(255) NOT NULL,
    ToLocation varchar(255) NOT NULL,
    ShipmentDescription varchar(255) NOT NULL,
    Attribute1 varchar(255) NULL,
    Attribute2 varchar(255) NULL,
    Attribute3 varchar(255) NULL,
    Attribute4 varchar(255) NULL,
    CostPerShipment float NULL,
    OtherCostPerShipment float NULL,
    FixedCostPerTrip float NULL,
    MinShipmentsPerPeriod float NULL,
    MaxShipmentsPerPeriod float NULL,
    MinTotalShipments float NULL,
    MaxTotalShipments float NULL,
    MinTotalTrips float NULL,
    MaxTotalTrips float NULL,
    TotalSolutionShipments float NULL,
    OppValuePerTotalSolutionShipments float NULL,
    TotalSolutionTrips float NULL,
    TotalTripFixedCost float NULL,
    TotalCost float NULL,
    TransitTime int NULL,
    TotalUnitsInTransitLastPeriod float NULL,
    VariableType varchar(255) NULL,
    ConstraintSet varchar(255) NULL,
    Tag1 varchar(255) NULL,
    Tag2 varchar(255) NULL,
    Tag3 varchar(255) NULL,
    Tag4 varchar(255) NULL
);