CREATE TABLE T_EO_I_RatioDefinitions (
    _ScenarioID INT NOT NULL,
    ObjectName VARCHAR(255) NOT NULL,
    _VariableControlledFacilityLocationAttribute VARCHAR(255) NULL,
    _Location VARCHAR(255) NULL,
    _Facility VARCHAR(255) NULL,
    _AttributeVariableTypeAndConstraintSetControl VARCHAR(255) NULL,
    _TransferCurrencyControl VARCHAR(255) NULL,
    _Attribute1 VARCHAR(255) NULL,
    _Attribute2 VARCHAR(255) NULL,
    _Attribute3 VARCHAR(255) NULL,
    _Attribute4 VARCHAR(255) NULL,
    _Tag1 VARCHAR(255) NULL,
    _Tag2 VARCHAR(255) NULL,
    _AnalysisFlag VARCHAR(255) NULL,
    _InventoryClass VARCHAR(255) NULL,
    _SingleSourceOptions VARCHAR(255) NULL,
    _SourceLimit FLOAT NULL,
    _SourcePenalty FLOAT NULL,
    _MaxSingleSourceExceptions FLOAT NULL,
    _ForceMinRatiosOnInventoriesDefaultValue VARCHAR(255) NULL,
    _PoolingFlag VARCHAR(255) NULL,
    _RatioBandingFlag VARCHAR(255) NULL,
    _ValueTaxRateBase VARCHAR(255) NULL,
    _AllocateValueTaxTo VARCHAR(255) NULL,
    _UseUnitCostDriverDefaultAccounts VARCHAR(255) NULL,
    _ObjectActive VARCHAR(255) NULL,
    _PropagateTagsToMTPTable VARCHAR(255) NULL,
    Facility VARCHAR(255) NULL,
    Location VARCHAR(255) NOT NULL,
    RatioName VARCHAR(255) NOT NULL,
    RatioBand VARCHAR(255) NULL,
    UseTotalVolumeAsDenominatorValue VARCHAR(255) NULL,
    ConstrainFlowIn VARCHAR(255)  NULL,
    ConstrainFlowOut VARCHAR(255)  NULL,
    ConstrainPeriodEndingVolumes VARCHAR(255)  NULL,
    ConstrainEndingVolumes VARCHAR(255)  NULL,
    ForceMinRatio VARCHAR(255)  NULL,
    Numerator VARCHAR(255) NULL,
    NumeratorValueEndingVolume FLOAT NULL,
    Denominator VARCHAR(255) NULL,
    DenominatorValueEndingVolume FLOAT NULL,
    MinRatio FLOAT NULL,
    MaxRatio FLOAT NULL,
    RatioEndingVolume FLOAT NULL,
    BandActivity FLOAT NULL,
    MinRatioBias FLOAT NULL,
    MinRatioNumeratorShortage FLOAT NULL,
    OppValueMinRatio FLOAT NULL,
    MaxRatioBias FLOAT NULL,
    MaxRatioDenominatorShortage FLOAT NULL,
    OppValueMaxRatio FLOAT NULL,
    ConstraintSet VARCHAR(255)  NULL,
    PoolingPrecision FLOAT NULL,
    PoolingPrecisionAdjustment FLOAT NULL,
    PoolingAdjustmentBias FLOAT NULL,
    PoolingMaxAdjustmentPerPeriod FLOAT NULL,
    PoolingMaxTotalAdjustment FLOAT NULL,
    PoolingTotalAdjustmentSolution FLOAT NULL,
    PoolingTotalAdjustmentOppValue FLOAT NULL
);