CREATE TABLE T_EO_ItI_ToShipmentDescription (
    _ScenarioID INT NOT NULL,
    ObjectName VARCHAR(120) NOT NULL,
    FromObjectName VARCHAR(255) NULL,
    ToObjectName VARCHAR(255) NULL,
    _VariableControlledFacilityLocationAttribute VARCHAR(255) NULL,
    _VariableTypeAndConstraintSetControl VARCHAR(255) NULL,
    _ForceIntegerTransfers VARCHAR(255) NULL,
    _TransferCurrencyControl VARCHAR(255) NULL,
    _Attribute1 VARCHAR(255) NULL,
    _Attribute2 VARCHAR(255) NULL,
    _Attribute3 VARCHAR(255) NULL,
    _Attribute4 VARCHAR(255) NULL,
    _Tag1 VARCHAR(255) NULL,
    _Tag2 VARCHAR(255) NULL,
    _Tag3 VARCHAR(255) NULL,
    _PropagateTagsToMTPTable VARCHAR(255) NULL,
    FromFacility VARCHAR(255) NULL,
    ToFacility VARCHAR(255) NULL,
    FromLocation VARCHAR(120) NOT NULL,
    ToLocation VARCHAR(120) NOT NULL,
    ShipmentDescription VARCHAR(255) NOT NULL,
    ToMaterial VARCHAR(255) NOT NULL,
    Tag1 VARCHAR(255) NULL,
    Tag2 VARCHAR(255) NULL,
    YieldUnitsPerShipment DOUBLE PRECISION NULL,
    SolutionUnits DOUBLE PRECISION NULL,
    TotalUnitsInTransitLastPeriod DOUBLE PRECISION NULL,
    CostingAllocation DOUBLE PRECISION NULL,
    AvgCostPerUnit DOUBLE PRECISION NULL
);