CREATE TABLE IF NOT EXISTS T_EO_P_PurchaseActivity (
    _ScenarioID INT,
    ObjectName VARCHAR(255) NOT NULL,
    _VariableControlledFacilityLocationAttribute VARCHAR(255),
    _Location VARCHAR(255),
    _Facility VARCHAR(255),
    _AttributeVariableTypeAndConstraintSetControl VARCHAR(255),
    _Attribute1 VARCHAR(255),
    _Attribute2 VARCHAR(255),
    _Attribute3 VARCHAR(255),
    _Attribute4 VARCHAR(255),
    _Tag1 VARCHAR(255),
    _Tag2 VARCHAR(255),
    _AnalysisFlag VARCHAR(255),
    _PurchaseClass VARCHAR(255),
    _UseUnitCostDriverDefaultAccounts VARCHAR(255),
    _DiscountApproximationSteps INT,
    _ObjectActive VARCHAR(255),
    _UseDiscountCurves VARCHAR(255),
    _ApplyDiscountCurvesGlobally VARCHAR(255),
    _ApplyGlobalDiscountCurvesToThisObject VARCHAR(255),
    _PropagateTagsToMTPTable VARCHAR(255),
    _PropagateTagsToMTPDiscountTable VARCHAR(255),
    Facility VARCHAR(255) ,
    Location VARCHAR(255) NOT NULL,
    ItemDescription VARCHAR(255) NOT NULL,
    Attribute1 VARCHAR(255),
    Attribute2 VARCHAR(255),
    Attribute3 VARCHAR(255),
    Attribute4 VARCHAR(255),
    CostPerUnit FLOAT,
    OtherCostPerUnit FLOAT,
    MinUnitsPerPeriod FLOAT,
    MaxUnitsPerPeriod FLOAT,
    MinTotalUnits FLOAT,
    MaxTotalUnits FLOAT,
    TotalSolutionUnits FLOAT,
    OppValuePerUnit FLOAT,
    TotalUnitCost FLOAT,
    TotalOtherCost FLOAT,
    TotalVolumeDiscounts FLOAT,
    TotalNetPurchases FLOAT,
    AvgNetCostPerUnit FLOAT,
    VariableType VARCHAR(255),
    ConstraintSet VARCHAR(255),
    ApproximationStepSize FLOAT,
    Tag1 VARCHAR(255),
    Tag2 VARCHAR(255),
    Tag3 VARCHAR(255),
    Tag4 VARCHAR(255)
);