CREATE TABLE t_eo_p_purchaseactivitymtp (
    _ScenarioID INT NOT NULL,
    objectname varchar(255) NOT NULL,
    _variablecontrolledfacilitylocationattribute varchar(255) NULL,
    _location varchar(255) NULL,
    _facility varchar(255) NULL,
    _attributevariabletypeandconstraintsetcontrol varchar(255) NULL,
    _attribute1 varchar(255) NULL,
    _attribute2 varchar(255) NULL,
    _attribute3 varchar(255) NULL,
    _attribute4 varchar(255) NULL,
    _tag1 varchar(255) NULL,
    _tag2 varchar(255) NULL,
    _analysisflag varchar(255) NULL,
    _purchaseclass varchar(255) NULL,
    _useunitcostdriverdefaultaccounts varchar(255) NULL,
    _discountapproximationsteps int NULL,
    _objectactive varchar(255) NULL,
    _usediscountcurves varchar(255) NULL,
    _applydiscountcurvesglobally varchar(255) NULL,
    _applyglobaldiscountcurvestothisobject varchar(255) NULL,
    _propagatetagstomtptable varchar(255) NULL,
    _propagatetagstomtpdiscounttable varchar(255) NULL,
    timeperiod varchar(32) NOT NULL,
    facility varchar(255) NULL,
    location varchar(255) NOT NULL,
    itemdescription varchar(255) NOT NULL,
    attribute1 varchar(255) NULL,
    attribute2 varchar(255) NULL,
    attribute3 varchar(255) NULL,
    attribute4 varchar(255) NULL,
    costperunit float NULL,
    othercostperunit float NULL,
    minunits float NULL,
    maxunits float NULL,
    solutionunits float NULL,
    oppvalueperunit float NULL,
    cost float NULL,
    othercost float NULL,
    volumediscounts float NULL,
    netpurchases float NULL,
    avgnetcostperunit float NULL,
    costperunitfactor float NULL,
    costperunitadd float NULL,
    othercostperunitfactor float NULL,
    othercostperunitadd float NULL,
    minunitsfactor float NULL,
    minunitsadd float NULL,
    maxunitsfactor float NULL,
    maxunitsadd float NULL,
    variabletype varchar(255) NULL,
    constraintset varchar(255) NULL,
    tag1 varchar(255) NULL,
    tag2 varchar(255) NULL,
    tag3 varchar(255) NULL,
    tag4 varchar(255) NULL
);
