CREATE TABLE IF NOT EXISTS T_EO_S_SalesActivityMTP (
    _ScenarioID INT NOT NULL,
    ObjectName VARCHAR(255) NOT NULL,
    TimePeriod VARCHAR(255) NOT NULL,
    Facility VARCHAR(255) NULL,
    Location VARCHAR(255) NOT NULL,
    ItemDescription VARCHAR(255) NOT NULL,
    Attribute1 VARCHAR(255) NULL,
    Attribute2 VARCHAR(255) NULL,
    Attribute3 VARCHAR(255) NULL,
    Attribute4 VARCHAR(255) NULL,
    PricePerUnit FLOAT NULL,
    DiscountReturnAndCommissionRate FLOAT NULL,
    MinUnits FLOAT NULL,
    MaxUnits FLOAT NULL,
    SolutionUnits FLOAT NULL,
    OppValuePerUnit FLOAT NULL,
    GrossSales FLOAT NULL,
    DiscountReturnAndCommission FLOAT NULL,
    VolumeDiscounts FLOAT NULL,
    NetSales FLOAT NULL,
    AvgNetSalesPerUnit FLOAT NULL,
    AvgCostPerUnit FLOAT NULL,
    AvgMarginPerUnit FLOAT NULL,
    PricePerUnitFactor FLOAT NULL,
    PricePerUnitAdd FLOAT NULL,
    DiscountReturnAndCommissionRateFactor FLOAT NULL,
    DiscountReturnAndCommissionRateAdd FLOAT NULL,
    MinUnitsFactor FLOAT NULL,
    MinUnitsAdd FLOAT NULL,
    MaxUnitsFactor FLOAT NULL,
    MaxUnitsAdd FLOAT NULL,
    VariableType VARCHAR(255) NULL,
    ConstraintSet VARCHAR(255) NULL,
    Tag1 VARCHAR(255) NULL,
    Tag2 VARCHAR(255) NULL,
    Tag3 VARCHAR(255) NULL,
    Tag4 VARCHAR(255) NULL


);

