CREATE TABLE IF NOT EXISTS T_EO_S_SalesActivity (
    _ScenarioID INTNOT NULL,
    ObjectName VARCHAR(255) NOT NULL,
    _VariableControlledFacilityLocationAttribute VARCHAR(255),
    _Location VARCHAR(255),
    _Facility VARCHAR(255),
    _AttributeVariableTypeAndConstraintSetControl VARCHAR(255),
    _Attribute1 VARCHAR(255),
    _Attribute2 VARCHAR(255),
    _Attribute3 VARCHAR(255),
    _Attribute4 VARCHAR(255),
    _Tag1 VARCHAR(255),
    _Tag2 VARCHAR(255),
    _AnalysisFlag VARCHAR(255),
    _SingleSourceOptions VARCHAR(255),
    _SourceLimit FLOAT,
    _SourcePenalty FLOAT,
    _MaxSingleSourceExceptions FLOAT,
    _DiscountApproximationSteps INT,
    _UseUnitCostDriverDefaultAccounts VARCHAR(255),
    _ObjectActive VARCHAR(255),
    _UseDiscountCurves VARCHAR(255),
    _ApplyDiscountCurvesGlobally VARCHAR(255),
    _ApplyGlobalDiscountCurvesToThisObject VARCHAR(255),
    _CompetitiveMarket VARCHAR(255),
    _PropagateTagsToMTPTable VARCHAR(255),
    _PropagateTagsToMTPDiscountTable VARCHAR(255),
    Facility VARCHAR(255),
    Location VARCHAR(255) NOT NULL,
    ItemDescription VARCHAR(255) NOT NULL,
    Attribute1 VARCHAR(255),
    Attribute2 VARCHAR(255),
    Attribute3 VARCHAR(255),
    Attribute4 VARCHAR(255),
    PricePerUnit FLOAT,
    DiscountReturnAndCommissionRate FLOAT,
    MinUnitsPerPeriod FLOAT,
    MaxUnitsPerPeriod FLOAT,
    MinTotalUnits FLOAT,
    MaxTotalUnits FLOAT,
    TotalSolutionUnits FLOAT,
    OppValuePerUnit FLOAT,
    TotalGrossSales FLOAT,
    TotalDiscountReturnAndCommission FLOAT,
    TotalVolumeDiscounts FLOAT,
    TotalNetSales FLOAT,
    AvgNetSalesPerUnit FLOAT,
    AvgCostPerUnit FLOAT,
    AvgMarginPerUnit FLOAT,
    CostOfGoodsSold FLOAT,
    VariableType VARCHAR(255),
    ConstraintSet VARCHAR(255),
    ApproximationStepSize FLOAT,
    Tag1 VARCHAR(255),
    Tag2 VARCHAR(255),
    Tag3 VARCHAR(255),
    Tag4 VARCHAR(255)

);
